// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSuiteLab.Models;

#nullable disable

namespace VSuiteLab.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260219063944_VALARMDatesUpdate")]
    partial class VALARMDatesUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("VSuiteLab.Models.CalDavAlarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavNoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavNoteId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Repeat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SelectedDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("SelectedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalDavNoteId");

                    b.HasIndex("CalDavNoteId1");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CalDavNoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavNoteId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Uri")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CalDavNoteId");

                    b.HasIndex("CalDavNoteId1");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavAttendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavNoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalDavNoteId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavNoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalDavNoteId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavNoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalDavNoteId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DavConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("uriUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DavConfigId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("VSuiteLab.Models.DavConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsVjournal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsVtodo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("httpUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavConfigs");
                });

            modelBuilder.Entity("VSuiteLab.Models.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetry")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SyncAuto")
                        .HasColumnType("REAL");

                    b.Property<bool>("SyncOnChange")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavAlarm", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavNote", null)
                        .WithMany("Alarms")
                        .HasForeignKey("CalDavNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSuiteLab.Models.CalDavNote", "CalDavNote")
                        .WithMany()
                        .HasForeignKey("CalDavNoteId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalDavNote");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavAttachment", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavNote", null)
                        .WithMany("Attachments")
                        .HasForeignKey("CalDavNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSuiteLab.Models.CalDavNote", "CalDavNote")
                        .WithMany()
                        .HasForeignKey("CalDavNoteId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalDavNote");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavAttendee", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavNote", null)
                        .WithMany("Attendees")
                        .HasForeignKey("CalDavNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavCategory", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavNote", null)
                        .WithMany("Categories")
                        .HasForeignKey("CalDavNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavComment", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavNote", null)
                        .WithMany("Comments")
                        .HasForeignKey("CalDavNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavNote", b =>
                {
                    b.HasOne("VSuiteLab.Models.DavConfig", "DavConfig")
                        .WithMany("Notes")
                        .HasForeignKey("DavConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavConfig");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavNote", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Attachments");

                    b.Navigation("Attendees");

                    b.Navigation("Categories");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("VSuiteLab.Models.DavConfig", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
