// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSuiteLab.Models.Contexts;

#nullable disable

namespace VSuiteLab.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260502020138_PreviousDavConfigId")]
    partial class PreviousDavConfigId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("VSuiteLab.Models.CalDavAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasRan")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Repeat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SelectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalDavItemId");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Uri")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CalDavItemId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavAttendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalDavItemId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalDavItemId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalDavItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalDavItemId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DavConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousDavConfigId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DavConfigId");

                    b.ToTable("CalDavItems", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VSuiteLab.Models.DavConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsVjournal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsVtodo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("httpUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavConfigs");
                });

            modelBuilder.Entity("VSuiteLab.Models.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConflictStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DebugEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SyncAuto")
                        .HasColumnType("REAL");

                    b.Property<bool>("SyncOnChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpdateDoNotAsk")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavJournal", b =>
                {
                    b.HasBaseType("VSuiteLab.Models.CalDavItem");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("CalDavJournals", (string)null);
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavNote", b =>
                {
                    b.HasBaseType("VSuiteLab.Models.CalDavItem");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("CalDavNotes", (string)null);
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavTask", b =>
                {
                    b.HasBaseType("VSuiteLab.Models.CalDavItem");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("CalDavTasks", (string)null);
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavAlarm", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavItem", "CalDavItem")
                        .WithMany("Alarms")
                        .HasForeignKey("CalDavItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalDavItem");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavAttachment", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavItem", "CalDavItem")
                        .WithMany("Attachments")
                        .HasForeignKey("CalDavItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalDavItem");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavAttendee", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavItem", "CalDavItem")
                        .WithMany("Attendees")
                        .HasForeignKey("CalDavItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalDavItem");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavCategory", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavItem", "CalDavItem")
                        .WithMany("Categories")
                        .HasForeignKey("CalDavItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalDavItem");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavComment", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavItem", "CalDavItem")
                        .WithMany("Comments")
                        .HasForeignKey("CalDavItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalDavItem");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavItem", b =>
                {
                    b.HasOne("VSuiteLab.Models.DavConfig", "DavConfig")
                        .WithMany("Items")
                        .HasForeignKey("DavConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavConfig");
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavJournal", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavItem", null)
                        .WithOne()
                        .HasForeignKey("VSuiteLab.Models.CalDavJournal", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavNote", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavItem", null)
                        .WithOne()
                        .HasForeignKey("VSuiteLab.Models.CalDavNote", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavTask", b =>
                {
                    b.HasOne("VSuiteLab.Models.CalDavItem", null)
                        .WithOne()
                        .HasForeignKey("VSuiteLab.Models.CalDavTask", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSuiteLab.Models.CalDavItem", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Attachments");

                    b.Navigation("Attendees");

                    b.Navigation("Categories");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("VSuiteLab.Models.DavConfig", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
